#  ## This is docker-compose file for the country-city service 
 version: "3.7"

 services:
   Nodejs/express: # backend/ frontend 
     image: 'nodejs'
     container_name: 'cityinfo' 
   # command: sh -c "npm install && npm run build && npm start"
     ports: 
       - "${hostPort}:${port}"
     working_dir: /storage/branches/${branch}
     volumes:
       - ${gitRepoName}-storage:/storage 
     environment: MONGO_CONNSTRING=mongodb://${secret.MONGODB_USERNAME}:${secret.MONGODB_PASSWORD}
      

   MongoDB:
     image: 'mongo'
     container_name: 'db-cityinfo'
     port: 
      - "${hostport}:27017"    
     volumes:
       - ${gitRepoName}-storage:/storage 
      #- mongodb-data:/data/db 
     environment:
      - MONGODB_INITDB_ROOT_USERNAME=${secret.MONGODB_USERNAME} 
      - MONGODB_INITDB_ROOT_PASSWORD=${secret.MONGODB_PASSWORD} 

 volumes:
 mongodb-data: